test-mock:
	node mockTime
	
test-paymentHistory:
	node paymentHistory/test1
	node paymentHistory/test2
	node paymentHistory/test3
	node paymentHistory/test4
	node paymentHistory/test4a
	node paymentHistory/test4b
	node paymentHistory/test5
	node paymentHistory/test6
	node paymentHistory/test7
	node paymentHistory/changePlan/test1
	node paymentHistory/changePlan/test2
	node paymentHistory/changePlan/test3
	node paymentHistory/changePlan/test4
	node paymentHistory/changePlan/test5
	node paymentHistory/changePlan/test6
	node paymentHistory/changePlan/test7
	node paymentHistory/changePlan/test8
	node paymentHistory/changePlan/test9
	node paymentHistory/changePlan/test10
	node paymentHistory/changePlan/test11

all : test-mock test-paymentHistory

